### ISSUE TITLE
midiin.getMessage(250) return None

### ISSUE THREAD

**Issue by gabofer82** [patrickkidd/pyrtmidi#20]
Hi:

I have a question, I'm very newbie in this informatic sound world.
This is the scenario:

I connect my Behringer UMX610 controller via USB to my computer.
I spect when I play the keyboard my script recieve the midi signal and will print into terminal using this code (from README with little changes):

```
midiin = rtmidi.RtMidiIn()


def print_message(midi):
    if midi.isNoteOn():
        print('(L9) ON: ', midi.getMidiNoteName(midi.getNoteNumber()), midi.getVelocity())
    elif midi.isNoteOff():
        print('(L10) OFF:', midi.getMidiNoteName(midi.getNoteNumber()))
    elif midi.isController():
        print('(L13) CONTROLLER', midi.getControllerNumber(), midi.getControllerValue())


ports = range(midiin.getPortCount())
if ports:
    for i in ports:
        print('(L19) ', midiin.getPortName(i))
    print("(L20) Opening port 0!")
    midiin.openPort(0, midiin.getPortName(i))
    while True:
        m = midiin.getMessage(250) # some timeout in ms
        print('(L24) Message', m)
        if m:
            print_message('(L23) ',m)
else:
    print('(L28) NO MIDI INPUT PORTS!')
```
But the output is:

```
(L19)  Midi Through 14:0
(L19)  UMX 610 24:0
(L20) Opening port 0!
(L24) Message None
(L24) Message None
.
.
.
.
```

I'm very thankful for any explanations about this, and any kind of documentation links in order to enlighten me about this topic.

Thankyou.

**Comment by patrickkidd** [comment]
You problem is a basic python problem, not a problem with the rtmidi module.

- The midi message you are trying to print files the three conditionals in print_message(), so print_message() doesn’t print anything.
- Then your print statement on L24 prints the return value getMessage(), which is None because it timed out waiting for a message. You can find information about this in the docs.

—Patrick

**Comment by gabofer82** [comment]
Thankyou Patrick for your quickly answer, but now I commented the L24 print:

   ```
 while True:
        m = midiin.getMessage(250) # some timeout in ms
        # print('(L24) Message', m)
        if m:
            print_message(m)
```
And then neither of the three statments of print_message() are executed...
I only add a print() for control, I doubt that this line make any problem..

Sorry for my my insistence, but if all run ok I will get the midi note that I'll be pressing on the keyboard?  (note number) right?

Thankyou for your time..

-Gabriel

**Comment by patrickkidd** [comment]
Again, your basic python logic does not satisfy the three if statements. You might do better to go through a basic python tutorial to understand conditional statements and function return values. It will be a more efficient use of your time than pursuing this problem here. This issue list is for problems with the rtmidi library, which is functioning properly.
